env:
  browser: true
  es6: true
  node: true
  jest: true
extends: 'eslint:recommended'
parser: 'babel-eslint'
parserOptions:
  ecmaFeatures:
    classes: true
    experimentalObjectRestSpread: true
    jsx: true
  sourceType: module
plugins:
  - mocha
  - react
rules:
  no-console:
    - error
    - allow:
      - warn
      - error
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  react/jsx-uses-vars: 1
  semi:
    - error
    - always
